services:
  api:
    build: .
    container_name: api-amburgueria
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://burguerfacil_user:vHnNN5rO6mnUuphnvDqastUDqlPoXzPU@dpg-d8v8t4bsq97s7381slmg-a.oregon-postgres.render.com:5432/burguerfacil?sslmode=require
      DB_HOST: dpg-d8v8t4bsq97s7381slmg-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_USERNAME: burguerfacil_user
      DB_PASSWORD: vHnNN5rO6mnUuphnvDqastUDqlPoXzPU
      DB_DATABASE: burguerfacil
      DB_SCHEMA: public
      DB_SSL: true
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    image: postgres:16-alpine
    container_name: amburgueria-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: andersonmendes
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ambuigueriadb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
