services:
  api:
    build: .
    container_name: api-amburgueria
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      # DATABASE_URL: postgresql://andersonmendes:root@postgres:5432/loog_system
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: andersonmendes
      DB_PASSWORD: root
      DB_DATABASE: ambuigueriadb
      DB_SCHEMA: public
      DB_SSL: false
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    image: postgres:16-alpine
    container_name: amburgueria-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: andersonmendes
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ambuigueriadb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
